Update dbClient to use db pool connections
Update for how we use node-postgres, to instead use DB pool connections
instead of indiv db client connections in order to avoid previous
error: "Client has already been connected" for csv agenda upload
functionality.